### ISSUE TITLE
Upgrade czech books and covers

### ISSUE THREAD

**Issue by dharmiks** [dharmiks/sri-chinmoy-library-cs#3]
@nirbhasa, could you please upgrade the czech archive, I have finished repairings of capital letters now. Also in english archive are cleaned many covers. Thanks

**Comment by nirbhasa** [comment]
Hi Dharmik - do you have covers specific for czech books? Are they in the jpg/pdf folders, or in another library?

**Comment by dharmiks** [comment]
Yes, czech covers are in the folder Seafile\cz-archives-covers\jpg, file-format is xxx-cs.jpg or xxxx-sk.jpg

**Comment by nirbhasa** [comment]
done

**Comment by dharmiks** [comment]
Thank you for upgrade of czech texts and english covers.
When I have checked pages, there are still not working:
- czech covers
- search according czech books( there is search according units). 
- on slovak pages is a structure of search for czech books according books but real search is according units
- recounting of units for czech SCA created uncompatibility with english original version
- link to original is not working properly - it is going thru additional czech page
- on english pages are covers with transcendental: mfs, rb

**Comment by dharmiks** [comment]
I have renamed rb with transcendental now, after upgrade it should be OK

**Comment by nirbhasa** [comment]
Thanks 

> czech covers
> Most Czech covers are there. The ones that aren’t is because Czech covers with different editions don’t have the exact cite key that is needed. I suggest that we give the most recent one the exact cite key. Then (for both English and Czech) we can show all versions of cover (and back) in a ‘lightbox’ slideshow - this will be done at future date
> search according czech books( there is search according units).
> on slovak pages is a structure of search for czech books according books but real search is according units
> to be clear - you want to be able to search for book titles only? Obviously the best thing is to have some kind of checkbox in the main search, but it we cant do that, it think it is quite easy to create separate search. 
> recounting of units for czech SCA created uncompatibility with english original version
> ok - does this need to be fixed in org mode file or in the site proper?
> link to original is not working properly - it is going thru additional czech page
> seems to be working fine for me - can you give an example
> on english pages are covers with transcendental: mfs, rb
> removed - thanks! Also afaf 

Need to think about how to stop this happening in future. The problem is I need to manually resize everything so it loads fast on web. 

Re citekey: good, I will put it back on foreign language pages. How do you want it displayed? With or without language tag? (Just to be clear - Priyadarshan said it is ok to have difference between how cite key looks in org mode files and on the web page. So definitely we are not changing it in the files themselves)

**Comment by dharmiks** [comment]
First a new thing - scrolling view on cz and pt pages is not working
- czech covers - It is funny, in my computer and also in mobil is not working at all. I see just with no pictures:

(1) | ( (1) | 1 (1226) | 2 (986) | 3 (717) | 4 (462) | 5 (349) | 6 (244) | 7 (178) | 8 (146) | 9 (144) | < (24) | A (79) | B (113) | Č (351) | D (125) | E (43) | F (3) | G (53) | H (28) | I (23) | J (569) | K (256) | L (31) | M (400) | N (194) | O (112) | P (302) | Q (1) | Ř (103) | S (216) | T (100) | Ú (41) | V (275) | W (1) | X (5) | Z (126) | “ (2) | „ (5)

```
1 of 268 další>
```

**Comment by dharmiks** [comment]
recounting of units for czech SCA created uncompatibility with english original version
ok - does this need to be fixed in org mode file or in the site proper?

In org mode file is still an old counting, we can use this.

**Comment by dharmiks** [comment]
search according czech books( there is search according units). on slovak pages is a structure of search for czech books according books but real search is according units

to be clear - you want to be able to search for book titles only? Obviously the best thing is to have some kind of checkbox in the main search, but it we cant do that, it think it is quite easy to create separate search.

I would like to have both version, but now I do not see version for book titles only

**Comment by nirbhasa** [comment]
scrolling, covers, link to titles - these are all working for me. There are 2 possibilities here:
- the ‘old’ version of site (before yesterdays updates) might be stuck in your browser cache and causing problems, so clear that
- it might be something to do with your operating system/browser, can you let me know what they are?

**Comment by dharmiks** [comment]
We have tried covers with Manavasu on different computers and browsers and it is not working

**Comment by dharmiks** [comment]
I have tried it on Android, Win 7 - Explorer and Mozila - all the same

**Comment by dharmiks** [comment]
Great, it works, thank you

**Comment by dharmiks** [comment]
I have repaired names in czech covers. Thanks.
